# Generated by Django 5.2.7 on 2025-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0004_alter_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
